groups:
  - name: production
    services:
      - displayName: Alertmanager
        localAddress: auto
        localPort: 29093
        servicePort: 9093
        namespace: monitoring-prometheus
        name: alertmanager-operated
        protocol: http
      - displayName: Prometheus
        localAddress: localhost
        localPort: 29090
        servicePort: 9090
        namespace: monitoring-prometheus
        name: prometheus-operated
        protocol: http
      - displayName: Grafana
        localAddress: 172.16.16.16
        localPort: 23000
        servicePort: 3000
        namespace: monitoring-prometheus
        name: prometheus-production-grafana
        protocol: http
      - displayName: Kibana
        localPort: 25601
        servicePort: 5601
        namespace: monitoring-eck
        name: kibana-kb-http
        protocol: http
      - displayName: Elasticsearch
        localPort: 29200
        servicePort: 9200
        namespace: monitoring-eck
        name: elasticsearch-es-http
        protocol: https
  - name: staging
    services:
      - displayName: Alertmanager
        localPort: 28093
        servicePort: 9093
        namespace: monitoring-prometheus
        name: alertmanager-operated
        protocol: http
      - displayName: Prometheus
        localPort: 28090
        servicePort: 9090
        namespace: monitoring-prometheus
        name: prometheus-operated
        protocol: http
      - displayName: Grafana
        localPort: 22000
        servicePort: 3000
        namespace: monitoring-prometheus
        name: prometheus-staging-grafana
        protocol: http
      - displayName: Kibana
        localPort: 24601
        servicePort: 5601
        namespace: monitoring-eck
        name: kibana-kb-http
        protocol: http
      - displayName: Elasticsearch
        localPort: 28200
        servicePort: 9200
        namespace: monitoring-eck
        name: elasticsearch-es-http
        protocol: https
